version: '3.8'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "3002:3002" # modify port only if needed also if modified make changes in frontend env file too
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/deuss_db
      - NODE_ENV=development # TODO: Change this in production
      - JWT_SECRET=change_this_in_production
      - SESSION_SECRET=change_this_in_production
      - COOKIE_DOMAIN=localhost
      - PORT=3002 # modify port only if needed also if modified make changes in frontend env file too
      # Email COnfiguration in prod only no need to configure if you are running locally
      - EMAIL_VERIFICATION=false # TODO: Change this in production
      - SMTP_FROM=noreply@mail.deuss.space # TODO: Change this in production
      - FRONTEND_URL=http://localhost # TODO: Change this in production
      - RESEND_API_KEY=re_00000000000000000000000000000000 # TODO: Change this in production
      - RESEND_FROM=noreply@mail.deuss.space # TODO: CHange this in production
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deuss_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c ssl=off

volumes:
  postgres_data:
